"""remove points cost from gift catalog and orders

Revision ID: 06531be12eb5
Revises: 50233f026db1
Create Date: 2026-08-29 17:12:19.458570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06531be12eb5'
down_revision: Union[str, None] = '50233f026db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gift_catalog_items', 'points_cost')
    op.drop_column('gift_orders', 'points_cost')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_orders', sa.Column('points_cost', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('gift_catalog_items', sa.Column('points_cost', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
