"""add birthday settings and birthday wish tracking

Revision ID: 1122e9e12117
Revises: b5074ff0ad6c
Create Date: 2026-09-06 10:25:37.981233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1122e9e12117'
down_revision: Union[str, None] = 'b5074ff0ad6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birthday_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('notify_days_before', sa.Integer(), server_default='3', nullable=False),
    sa.Column('auto_send_message', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('message_template', sa.String(length=500), server_default='Happy Birthday, {{customer_name}}! Wishing you a wonderful year ahead. 🎉', nullable=False),
    sa.Column('auto_assign_gift', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('customers', sa.Column('last_birthday_wish_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'last_birthday_wish_year')
    op.drop_table('birthday_settings')
    # ### end Alembic commands ###
