"""add slug and published to forms

Revision ID: 1c0b3ec1cca3
Revises: d34695341b60
Create Date: 2026-08-29 14:46:32.049536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c0b3ec1cca3'
down_revision: Union[str, None] = 'd34695341b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forms', sa.Column('slug', sa.String(length=255), nullable=True))
    op.add_column('forms', sa.Column('published', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_forms_slug'), 'forms', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forms_slug'), table_name='forms')
    op.drop_column('forms', 'published')
    op.drop_column('forms', 'slug')
    # ### end Alembic commands ###
