"""add sms campaigns table

Revision ID: 1eee67034fae
Revises: bd5f9546308d
Create Date: 2026-08-19 16:53:30.081208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eee67034fae'
down_revision: Union[str, None] = 'bd5f9546308d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('audience_filter', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sender_id', sa.String(length=20), nullable=False),
    sa.Column('total_recipients', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sms_segments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_campaigns_public_id'), 'sms_campaigns', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sms_campaigns_public_id'), table_name='sms_campaigns')
    op.drop_table('sms_campaigns')
    # ### end Alembic commands ###
