"""add delivery address to gift orders

Revision ID: 50233f026db1
Revises: 43170dae3718
Create Date: 2026-08-29 16:58:42.787555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50233f026db1'
down_revision: Union[str, None] = '43170dae3718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_orders', sa.Column('delivery_address', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gift_orders', 'delivery_address')
    # ### end Alembic commands ###
