"""add image_path to gift_catalog_items

Revision ID: 510159fe54b4
Revises: cd441bfb9520
Create Date: 2026-08-25 16:39:43.040409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510159fe54b4'
down_revision: Union[str, None] = 'cd441bfb9520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_catalog_items', sa.Column('image_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gift_catalog_items', 'image_path')
    # ### end Alembic commands ###
