"""customer_types gain is_active

Revision ID: 58b5141c36e9
Revises: 4ab34f0bffe6
Create Date: 2026-09-03 15:29:54.253924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58b5141c36e9'
down_revision: Union[str, None] = '4ab34f0bffe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer_types', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer_types', 'is_active')
    # ### end Alembic commands ###
