"""add mailchimp marketing sync (customer opt-in, mailchimp_campaigns) and retire mandrill

Revision ID: 873ff9763512
Revises: c669523b9a63
Create Date: 2026-09-02 12:31:16.539450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '873ff9763512'
down_revision: Union[str, None] = 'c669523b9a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailchimp_campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('mailchimp_campaign_id', sa.String(length=50), nullable=False),
    sa.Column('mailchimp_segment_id', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailchimp_campaigns_public_id'), 'mailchimp_campaigns', ['public_id'], unique=True)
    op.create_index(op.f('ix_mailchimp_campaigns_status'), 'mailchimp_campaigns', ['status'], unique=False)
    op.add_column('customers', sa.Column('marketing_opt_in', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('customers', sa.Column('marketing_opt_in_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('customers', sa.Column('mailchimp_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'mailchimp_synced_at')
    op.drop_column('customers', 'marketing_opt_in_at')
    op.drop_column('customers', 'marketing_opt_in')
    op.drop_index(op.f('ix_mailchimp_campaigns_status'), table_name='mailchimp_campaigns')
    op.drop_index(op.f('ix_mailchimp_campaigns_public_id'), table_name='mailchimp_campaigns')
    op.drop_table('mailchimp_campaigns')
    # ### end Alembic commands ###
