"""campaign verification and landing pages

Revision ID: 8ba1e50a2fdc
Revises: 38b1f9e91d12
Create Date: 2026-08-26 17:04:44.973691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ba1e50a2fdc'
down_revision: Union[str, None] = '38b1f9e91d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_landing_pages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('builder_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{"version": 1, "blocks": []}', nullable=False),
    sa.Column('published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id')
    )
    op.create_index(op.f('ix_campaign_landing_pages_public_id'), 'campaign_landing_pages', ['public_id'], unique=True)
    op.create_index(op.f('ix_campaign_landing_pages_slug'), 'campaign_landing_pages', ['slug'], unique=True)
    op.add_column('campaign_recipients', sa.Column('verification_status', sa.String(length=20), server_default='PENDING', nullable=False))
    op.add_column('campaign_recipients', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_campaign_recipients_verification_status'), 'campaign_recipients', ['verification_status'], unique=False)
    op.add_column('customer_profile_tokens', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_customer_profile_tokens_campaign_id'), 'customer_profile_tokens', ['campaign_id'], unique=False)
    op.create_foreign_key(
        'fk_customer_profile_tokens_campaign_id_campaigns',
        'customer_profile_tokens', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_customer_profile_tokens_campaign_id_campaigns',
        'customer_profile_tokens', type_='foreignkey'
    )
    op.drop_index(op.f('ix_customer_profile_tokens_campaign_id'), table_name='customer_profile_tokens')
    op.drop_column('customer_profile_tokens', 'campaign_id')
    op.drop_index(op.f('ix_campaign_recipients_verification_status'), table_name='campaign_recipients')
    op.drop_column('campaign_recipients', 'verified_at')
    op.drop_column('campaign_recipients', 'verification_status')
    op.drop_index(op.f('ix_campaign_landing_pages_slug'), table_name='campaign_landing_pages')
    op.drop_index(op.f('ix_campaign_landing_pages_public_id'), table_name='campaign_landing_pages')
    op.drop_table('campaign_landing_pages')
    # ### end Alembic commands ###
