"""add brand_color to site_settings

Revision ID: 8ce8139e72e5
Revises: a22e51b1ebfe
Create Date: 2026-08-30 16:34:55.580852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ce8139e72e5'
down_revision: Union[str, None] = 'a22e51b1ebfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('site_settings', sa.Column('brand_color', sa.String(length=7), server_default='#EF4444', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('site_settings', 'brand_color')
    # ### end Alembic commands ###
