"""drop mailchimp template fields from campaigns

Revision ID: 95edd2740242
Revises: 632d3a196682
Create Date: 2026-09-07 18:27:54.860045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95edd2740242'
down_revision: Union[str, None] = '632d3a196682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'mailchimp_template_id')
    op.drop_column('campaigns', 'mailchimp_template_sections')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('mailchimp_template_sections', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('mailchimp_template_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
