"""add campaign channel and message templates

Revision ID: 9d5ef0f108f4
Revises: 8ce8139e72e5
Create Date: 2026-08-31 16:50:47.934947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d5ef0f108f4'
down_revision: Union[str, None] = '8ce8139e72e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_templates_channel'), 'message_templates', ['channel'], unique=False)
    op.create_index(op.f('ix_message_templates_public_id'), 'message_templates', ['public_id'], unique=True)
    op.add_column('campaign_recipients', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('campaigns', sa.Column('channel', sa.String(length=10), server_default='SMS', nullable=False))
    op.add_column('campaigns', sa.Column('subject', sa.String(length=255), nullable=True))
    op.alter_column('campaigns', 'sender_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_campaigns_channel'), 'campaigns', ['channel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaigns_channel'), table_name='campaigns')
    op.alter_column('campaigns', 'sender_id',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('campaigns', 'subject')
    op.drop_column('campaigns', 'channel')
    op.drop_column('campaign_recipients', 'email')
    op.drop_index(op.f('ix_message_templates_public_id'), table_name='message_templates')
    op.drop_index(op.f('ix_message_templates_channel'), table_name='message_templates')
    op.drop_table('message_templates')
    # ### end Alembic commands ###
