"""add wish text to gift orders

Revision ID: a22e51b1ebfe
Revises: 06531be12eb5
Create Date: 2026-08-30 11:08:13.622407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a22e51b1ebfe'
down_revision: Union[str, None] = '06531be12eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gift_orders', sa.Column('wish_text', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gift_orders', 'wish_text')
    # ### end Alembic commands ###
