"""add mailchimp_synced_at to customers

Revision ID: b5074ff0ad6c
Revises: e17b48615b3d
Create Date: 2026-09-05 12:26:46.906367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5074ff0ad6c'
down_revision: Union[str, None] = 'e17b48615b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('mailchimp_synced_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'mailchimp_synced_at')
    # ### end Alembic commands ###
