"""add customer_type to customers and import_batches

Revision ID: bd5f9546308d
Revises: cc1f03ae8273
Create Date: 2026-08-19 15:53:29.200678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd5f9546308d'
down_revision: Union[str, None] = 'cc1f03ae8273'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('customer_type', sa.String(length=20), server_default='GENERAL', nullable=False))
    op.add_column('import_batches', sa.Column('customer_type', sa.String(length=20), server_default='GENERAL', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_batches', 'customer_type')
    op.drop_column('customers', 'customer_type')
    # ### end Alembic commands ###
