"""add bounced status and delivery tracking to campaign_recipients

Revision ID: c669523b9a63
Revises: 6f3ac87dfefa
Create Date: 2026-09-02 11:07:09.376999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c669523b9a63'
down_revision: Union[str, None] = '6f3ac87dfefa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_recipients', sa.Column('bounced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaign_recipients', sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('campaign_recipients', sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_campaign_recipients_provider_message_id'), 'campaign_recipients', ['provider_message_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_campaign_recipients_provider_message_id'), table_name='campaign_recipients')
    op.drop_column('campaign_recipients', 'clicked_at')
    op.drop_column('campaign_recipients', 'opened_at')
    op.drop_column('campaign_recipients', 'bounced_at')
    # ### end Alembic commands ###
