"""add gift catalog and gift orders tables

Revision ID: cd441bfb9520
Revises: a8a417c26eda
Create Date: 2026-08-25 12:09:01.857874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd441bfb9520'
down_revision: Union[str, None] = 'a8a417c26eda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_catalog_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('retail_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('times_redeemed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gift_catalog_items_category'), 'gift_catalog_items', ['category'], unique=False)
    op.create_index(op.f('ix_gift_catalog_items_public_id'), 'gift_catalog_items', ['public_id'], unique=True)
    op.create_table('gift_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('catalog_item_id', sa.Integer(), nullable=True),
    sa.Column('gift_name', sa.String(length=255), nullable=False),
    sa.Column('points_cost', sa.Integer(), nullable=False),
    sa.Column('occasion', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('scheduled_for', sa.Date(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['catalog_item_id'], ['gift_catalog_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gift_orders_customer_id', 'gift_orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_gift_orders_public_id'), 'gift_orders', ['public_id'], unique=True)
    op.create_index(op.f('ix_gift_orders_status'), 'gift_orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gift_orders_status'), table_name='gift_orders')
    op.drop_index(op.f('ix_gift_orders_public_id'), table_name='gift_orders')
    op.drop_index('ix_gift_orders_customer_id', table_name='gift_orders')
    op.drop_table('gift_orders')
    op.drop_index(op.f('ix_gift_catalog_items_public_id'), table_name='gift_catalog_items')
    op.drop_index(op.f('ix_gift_catalog_items_category'), table_name='gift_catalog_items')
    op.drop_table('gift_catalog_items')
    # ### end Alembic commands ###
