"""add deliveries table

Revision ID: d34695341b60
Revises: a7adf4a10fea
Create Date: 2026-08-29 12:40:57.901449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd34695341b60'
down_revision: Union[str, None] = 'a7adf4a10fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('gift_order_id', sa.Integer(), nullable=False),
    sa.Column('courier', sa.String(length=30), nullable=False),
    sa.Column('tracking_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING_PICKUP', nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('estimated_delivery', sa.Date(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['gift_order_id'], ['gift_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deliveries_gift_order_id'), 'deliveries', ['gift_order_id'], unique=True)
    op.create_index(op.f('ix_deliveries_public_id'), 'deliveries', ['public_id'], unique=True)
    op.create_index(op.f('ix_deliveries_status'), 'deliveries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deliveries_status'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_public_id'), table_name='deliveries')
    op.drop_index(op.f('ix_deliveries_gift_order_id'), table_name='deliveries')
    op.drop_table('deliveries')
    # ### end Alembic commands ###
