"""add campaigns and campaign recipients

Revision ID: e013863e9e3f
Revises: 1eee67034fae
Create Date: 2026-08-19 17:39:49.625546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e013863e9e3f'
down_revision: Union[str, None] = '1eee67034fae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('campaign_type', sa.String(length=30), nullable=False),
    sa.Column('audience_rule_type', sa.String(length=30), nullable=False),
    sa.Column('audience_rule_params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('sender_id', sa.String(length=20), nullable=False),
    sa.Column('total_recipients', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sms_segments', sa.Integer(), server_default='0', nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('recipients_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_campaign_type'), 'campaigns', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_campaigns_public_id'), 'campaigns', ['public_id'], unique=True)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_table('campaign_recipients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='PENDING', nullable=False),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'customer_id', name='uq_campaign_recipients_campaign_customer')
    )
    op.create_index(op.f('ix_campaign_recipients_campaign_id'), 'campaign_recipients', ['campaign_id'], unique=False)
    op.create_index('ix_campaign_recipients_customer_id', 'campaign_recipients', ['customer_id'], unique=False)
    op.create_index(op.f('ix_campaign_recipients_public_id'), 'campaign_recipients', ['public_id'], unique=True)
    op.create_index(op.f('ix_campaign_recipients_status'), 'campaign_recipients', ['status'], unique=False)
    op.drop_index('ix_sms_campaigns_public_id', table_name='sms_campaigns')
    op.drop_table('sms_campaigns')
    op.create_index(op.f('ix_customers_created_at'), 'customers', ['created_at'], unique=False)
    op.create_index(op.f('ix_customers_customer_type'), 'customers', ['customer_type'], unique=False)
    op.create_index('ix_customers_missing_address', 'customers', ['id'], unique=False, postgresql_where=sa.text('address IS NULL'))
    op.create_index('ix_customers_missing_dob', 'customers', ['id'], unique=False, postgresql_where=sa.text('date_of_birth IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_missing_dob', table_name='customers', postgresql_where=sa.text('date_of_birth IS NULL'))
    op.drop_index('ix_customers_missing_address', table_name='customers', postgresql_where=sa.text('address IS NULL'))
    op.drop_index(op.f('ix_customers_customer_type'), table_name='customers')
    op.drop_index(op.f('ix_customers_created_at'), table_name='customers')
    op.create_table('sms_campaigns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('audience_filter', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('total_recipients', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('sms_segments', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('estimated_cost', sa.NUMERIC(precision=12, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False),
    sa.Column('scheduled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'DRAFT'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='sms_campaigns_pkey')
    )
    op.create_index('ix_sms_campaigns_public_id', 'sms_campaigns', ['public_id'], unique=True)
    op.drop_index(op.f('ix_campaign_recipients_status'), table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_public_id'), table_name='campaign_recipients')
    op.drop_index('ix_campaign_recipients_customer_id', table_name='campaign_recipients')
    op.drop_index(op.f('ix_campaign_recipients_campaign_id'), table_name='campaign_recipients')
    op.drop_table('campaign_recipients')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_public_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_type'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
