"""customers gain a separate city field

Revision ID: e17b48615b3d
Revises: 58b5141c36e9
Create Date: 2026-09-05 11:56:35.406049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17b48615b3d'
down_revision: Union[str, None] = '58b5141c36e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('city', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'city')
    # ### end Alembic commands ###
