"""add mailchimp template fields to campaigns

Revision ID: e23bef7ae009
Revises: 9be054068614
Create Date: 2026-09-07 11:37:53.647522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e23bef7ae009'
down_revision: Union[str, None] = '9be054068614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('mailchimp_template_id', sa.Integer(), nullable=True))
    op.add_column('campaigns', sa.Column('mailchimp_template_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'mailchimp_template_sections')
    op.drop_column('campaigns', 'mailchimp_template_id')
    # ### end Alembic commands ###
