"""replace mailchimp marketing with sendgrid

Revision ID: f1c86ee32246
Revises: 873ff9763512
Create Date: 2026-09-02 13:31:21.039501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1c86ee32246'
down_revision: Union[str, None] = '873ff9763512'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sendgrid_campaigns',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('sendgrid_campaign_id', sa.String(length=50), nullable=False),
    sa.Column('sendgrid_list_id', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sendgrid_campaigns_public_id'), 'sendgrid_campaigns', ['public_id'], unique=True)
    op.create_index(op.f('ix_sendgrid_campaigns_status'), 'sendgrid_campaigns', ['status'], unique=False)
    op.drop_index('ix_mailchimp_campaigns_public_id', table_name='mailchimp_campaigns')
    op.drop_index('ix_mailchimp_campaigns_status', table_name='mailchimp_campaigns')
    op.drop_table('mailchimp_campaigns')
    # True rename (not drop+add) — preserves any already-recorded sync
    # timestamps instead of silently discarding them.
    op.alter_column('customers', 'mailchimp_synced_at', new_column_name='marketing_synced_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'marketing_synced_at', new_column_name='mailchimp_synced_at')
    op.create_table('mailchimp_campaigns',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mailchimp_campaign_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mailchimp_segment_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('from_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('from_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('html_body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recipient_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'DRAFT'::character varying"), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='mailchimp_campaigns_pkey')
    )
    op.create_index('ix_mailchimp_campaigns_status', 'mailchimp_campaigns', ['status'], unique=False)
    op.create_index('ix_mailchimp_campaigns_public_id', 'mailchimp_campaigns', ['public_id'], unique=True)
    op.drop_index(op.f('ix_sendgrid_campaigns_status'), table_name='sendgrid_campaigns')
    op.drop_index(op.f('ix_sendgrid_campaigns_public_id'), table_name='sendgrid_campaigns')
    op.drop_table('sendgrid_campaigns')
    # ### end Alembic commands ###
